version: '3.7'
services:
  sonarqube:
    image: sonarqube:community  # Use the Community Edition image
    ports:
      - 9000:9000
    volumes:
      - sonarqube_data:/opt/sonarqube/data
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://postgresql:5432/sonarqube  # Connect to PostgreSQL container
      - SONAR_JDBC_USERNAME=sonarqube
      - SONAR_JDBC_PASSWORD=sonarqube
    networks:
      - sonarqube-network

  postgresql:  # PostgreSQL database service
    image: postgres
    environment:
      - POSTGRES_USER=sonarqube
      - POSTGRES_PASSWORD=sonarqube
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    networks:
      - sonarqube-network

volumes:
  sonarqube_data:
  postgresql_data:

# add network name sonarqube-network
networks:
  sonarqube-network: